export const LEARNING_CONTENT = {
  modules: [
    {
      id: 'app-shell',
      title: '应用入口',
      category: 'Shell',
      file: 'js/app.js',
      summary: '负责启动整个应用，创建视图容器、挂载导航、注册路由并完成启动时的一次性初始化。',
      whyItMatters: '当你想回答“这个应用从哪里开始跑起来”时，这就是第一站。',
      responsibilities: [
        '初始化导航和页面容器',
        '注册所有 route -> view 的映射',
        '启动当前路由并设置标题',
        '注册 Service Worker 并清理旧录音',
      ],
      inputs: ['index.html 里的 #nav / #main', 'window.CURRENT_LESSON'],
      outputs: ['已初始化的各个 view', '可工作的 Router', '启动后的应用壳层'],
      dependsOn: ['routing', 'home-view', 'practice-plan', 'recorder'],
      followUp: ['routing', 'home-view'],
      concepts: ['entry-point', 'routing', 'view'],
      inspect: '先看 init() 怎么创建 view 容器，再看 routeMap 怎样把 URL 接到具体模块。',
    },
    {
      id: 'routing',
      title: '路由器',
      category: 'Shell',
      file: 'js/router.js',
      summary: '根据 hash 变化决定当前显示哪个视图，并调用对应模块的 show / hide。',
      whyItMatters: '它解释了“为什么切换 URL，页面会变”。',
      responsibilities: [
        '监听 hashchange',
        '匹配静态路由和带参数的路由',
        '切换当前激活的 view',
      ],
      inputs: ['location.hash', 'register(pattern, handler)'],
      outputs: ['当前活动 view', '传给 view 的 params'],
      dependsOn: [],
      followUp: ['home-view'],
      concepts: ['routing', 'view'],
      inspect: '重点看 _resolve()、_matchPattern()、_activate() 三个方法如何分工。',
    },
    {
      id: 'event-bus',
      title: '事件总线',
      category: 'Shell',
      file: 'js/event-bus.js',
      summary: '提供 emit / on / off 这样的发布订阅机制，让不同模块通过事件协作。',
      whyItMatters: '它帮助你理解“模块之间为什么不用彼此直接 import 也能协同工作”。',
      responsibilities: [
        '注册事件监听函数',
        '广播事件给多个订阅者',
        '在交互结束时取消订阅，避免残留监听',
      ],
      inputs: ['事件名', '事件 payload'],
      outputs: ['被触发的监听器'],
      dependsOn: [],
      followUp: ['practice-player', 'home-view'],
      concepts: ['event-bus'],
      inspect: '先把它看成轻量消息中心，再回到 home-view 看 practice:beat 是怎么被消费的。',
    },
    {
      id: 'lesson-data',
      title: '课程数据',
      category: 'Data',
      file: 'data/lesson-current.js',
      summary: '用静态对象保存当前周的课程配置，是今天练什么、每段练多久的原始来源。',
      whyItMatters: '你改这里的内容，首页和周计划会随之变化。',
      responsibilities: [
        '提供 lesson 标题、日期和 teacher notes',
        '提供 open strings、piece、progression 等数据',
        '作为当前产品单课程模式的唯一课程入口',
      ],
      inputs: ['教师或产品定义好的课程内容'],
      outputs: ['window.CURRENT_LESSON'],
      dependsOn: [],
      followUp: ['practice-plan'],
      concepts: ['data-model', 'single-source-of-truth'],
      inspect: '先看 progression.day1 ~ day7，再看每个练习 section 的字段如何被下游使用。',
    },
    {
      id: 'practice-plan',
      title: '练习计划生成',
      category: 'Data',
      file: 'js/practice-plan.js',
      summary: '把课程配置转换成“今天该练什么”的页面模型。',
      whyItMatters: '它是数据和 UI 之间的第一层翻译器。',
      responsibilities: [
        '计算 day number',
        '生成 daily plan 和 weekly overview',
        '把 lesson 数据整理成页面需要的 section 结构',
      ],
      inputs: ['window.CURRENT_LESSON', '日期 / day number'],
      outputs: ['generateDailyPlan()', 'getWeekOverview()'],
      dependsOn: ['lesson-data'],
      followUp: ['home-view'],
      concepts: ['data-model', 'view-model'],
      inspect: '你要关心的不是语法，而是“输入 lesson，输出 plan”的结构变化。',
    },
    {
      id: 'home-view',
      title: '首页装配层',
      category: 'UI',
      file: 'js/ui/home-view.js',
      summary: '把今日计划渲染成卡片，并把播放、录音、勾选完成等交互接到具体模块上。',
      whyItMatters: '它像一个 orchestrator，把很多能力拼成用户看到的首页。',
      responsibilities: [
        '读取 daily plan 并渲染 section 卡片',
        '绑定播放、节拍器、参考音、录音和完成状态',
        '监听 EventBus，把播放状态同步回 UI',
      ],
      inputs: ['daily plan', 'practicePlayer.state', 'Tracking', 'Recorder'],
      outputs: ['首页 DOM', '交互绑定后的练习体验'],
      dependsOn: ['practice-plan', 'practice-player', 'score-utils', 'tracking', 'recorder'],
      followUp: ['practice-player', 'tracking', 'recorder'],
      concepts: ['view', 'event-bus', 'view-model'],
      inspect: '先读 show() 和 render()，再看 renderPieceSection() / renderStringsSection() 怎样把动作接出去。',
    },
    {
      id: 'practice-player',
      title: '播放状态机',
      category: 'Playback',
      file: 'js/practice-player.js',
      summary: '统一管理参考音、节拍器和示范播放，避免多个播放模式互相打架。',
      whyItMatters: '它是播放域里的 single source of truth。',
      responsibilities: [
        '维护 idle / reference / click / demo 四种模式',
        '开启和停止播放 session',
        '发出 beat 与 notechange 事件，驱动 UI 高亮',
      ],
      inputs: ['sectionId', 'bpm', 'pitch', 'timeline'],
      outputs: ['practice:statechange', 'practice:beat', 'practice:notechange'],
      dependsOn: ['audio-engine', 'score-utils', 'event-bus'],
      followUp: ['audio-engine', 'score-utils'],
      concepts: ['state', 'single-source-of-truth', 'event-bus'],
      inspect: '重点理解 startDemo()、toggleClick() 和 _stopSession() 怎样保证模式互斥。',
    },
    {
      id: 'audio-engine',
      title: '音频底层',
      category: 'Playback',
      file: 'js/audio-engine.js',
      summary: '直接和 Web Audio API 打交道，负责真正发声和调度。',
      whyItMatters: '如果播放器是指挥，audio-engine 就是演奏者。',
      responsibilities: [
        '管理 AudioContext 的创建与恢复',
        '合成参考音和节拍器 click',
        '调度示范播放的音序事件',
      ],
      inputs: ['pitch', 'bpm', 'timeline events'],
      outputs: ['浏览器里的实际声音'],
      dependsOn: [],
      followUp: ['practice-player'],
      concepts: ['state', 'timeline'],
      inspect: '当你以后学音频交互时，这里是理解浏览器发声机制的关键入口。',
    },
    {
      id: 'score-utils',
      title: '乐谱时间线',
      category: 'Playback',
      file: 'js/score-utils.js',
      summary: '把 measures 转成 UI 可画的 score model，以及播放器可调度的 timeline。',
      whyItMatters: '它把“乐谱长什么样”和“播放顺序是什么”这两件事连起来。',
      responsibilities: [
        '把音符时值换算成 beats',
        '生成 buildScoreModel() 用于页面渲染',
        '生成 buildPlaybackTimeline() 用于 demo 播放',
      ],
      inputs: ['measures', 'beatsPerMeasure'],
      outputs: ['score model', 'timeline events'],
      dependsOn: [],
      followUp: ['home-view', 'practice-player'],
      concepts: ['data-model', 'view-model', 'timeline'],
      inspect: '留意 noteIndex、startOffsetBeats、endOffsetBeats 这些字段，它们是 UI 和播放的桥。',
    },
    {
      id: 'music-theory',
      title: '乐理辅助',
      category: 'Learning',
      file: 'js/music-theory.js',
      summary: '把速度、休止符、拍号等知识包装成初学者能直接读懂的解释。',
      whyItMatters: '它体现了“给用户解释概念”也是代码职责，而不只是文案堆积。',
      responsibilities: [
        '提供 THEORY_TOPICS 数据',
        '生成人类可读的速度标签和拍号解释',
        '把前置休止转换成练习时可读提示',
      ],
      inputs: ['bpm', 'speedFactor', 'measures'],
      outputs: ['UI 文案', '学习提示'],
      dependsOn: ['score-utils'],
      followUp: ['home-view'],
      concepts: ['data-model', 'view-model'],
      inspect: '你可以从 THEORY_TOPICS 开始，因为它最容易改，也最容易立刻看到结果。',
    },
    {
      id: 'tracking',
      title: '进度追踪',
      category: 'Persistence',
      file: 'js/tracking.js',
      summary: '保存每日练习完成情况和统计数据，支撑首页勾选与进度页。',
      whyItMatters: '它回答了“我的操作如何在刷新后还记得”。',
      responsibilities: [
        '保存 section 完成状态',
        '保存 day 完成状态和累计时长',
        '提供 streak、completed days 等统计查询',
      ],
      inputs: ['weekOf', 'dayNumber', 'sectionId', 'elapsed'],
      outputs: ['localStorage 中的进度数据', '统计结果'],
      dependsOn: [],
      followUp: ['home-view'],
      concepts: ['persistence', 'state'],
      inspect: '读 toggleSection() 与 isDayCompleted()，先理解数据键是什么，再看统计怎么聚合。',
    },
    {
      id: 'recorder',
      title: '录音持久化',
      category: 'Persistence',
      file: 'js/recorder.js',
      summary: '封装 MediaRecorder 和 IndexedDB，把练习录音存到本地。',
      whyItMatters: '这是浏览器里比较接近“设备能力”的一层。',
      responsibilities: [
        '启动与停止录音',
        '把 Blob 写入 IndexedDB',
        '读取、删除和清理旧录音',
      ],
      inputs: ['MediaRecorder stream', 'exerciseId', 'weekOf', 'dayNumber'],
      outputs: ['IndexedDB 里的 recordings'],
      dependsOn: [],
      followUp: ['home-view'],
      concepts: ['persistence', 'state'],
      inspect: '如果你以后想碰文件、摄像头、麦克风，这类模块会很常见。',
    },
  ],
  flows: [
    {
      id: 'daily-plan',
      title: '从打开应用到看到今日练习',
      summary: '理解静态课程数据是如何变成首页卡片的。',
      moduleIds: ['app-shell', 'lesson-data', 'practice-plan', 'home-view'],
      steps: [
        {
          title: '应用启动',
          moduleId: 'app-shell',
          detail: '创建 view 容器，注册 routeMap，并启动 Router。',
        },
        {
          title: '课程数据进入运行时',
          moduleId: 'lesson-data',
          detail: '通过 window.CURRENT_LESSON 暴露当前课程配置。',
        },
        {
          title: '生成今日计划',
          moduleId: 'practice-plan',
          detail: '根据 day number 和 lesson progression 生成 daily plan。',
        },
        {
          title: '首页渲染卡片',
          moduleId: 'home-view',
          detail: '把 section 变成用户看到的练习卡片和交互按钮。',
        },
      ],
      starterQuestion: '如果今天的 section 顺序不对，你最先该检查哪一层？',
    },
    {
      id: 'piece-demo',
      title: '点一下示范播放后发生了什么',
      summary: '理解 UI 点击、播放状态机、时间线和音频调度之间的分工。',
      moduleIds: ['home-view', 'score-utils', 'practice-player', 'audio-engine'],
      steps: [
        {
          title: '按钮事件从 UI 发起',
          moduleId: 'home-view',
          detail: '首页点击示范播放后，把 section、速度和拍号交给 practicePlayer。',
        },
        {
          title: '乐谱转成 timeline',
          moduleId: 'score-utils',
          detail: '根据 measures 计算每个 note 的 startOffsetBeats。',
        },
        {
          title: '播放状态机接管 session',
          moduleId: 'practice-player',
          detail: '开始 demo 模式，安排 beat 事件和 notechange 事件。',
        },
        {
          title: '音频层真正发声',
          moduleId: 'audio-engine',
          detail: '根据 timeline 和 bpm 调度真实的音频播放。',
        },
      ],
      starterQuestion: '为什么 demo 和 click 不能同时开？',
    },
    {
      id: 'completion-tracking',
      title: '勾选完成后数据去哪了',
      summary: '理解 UI 操作如何落入本地状态，再反映到首页和进度页。',
      moduleIds: ['home-view', 'tracking'],
      steps: [
        {
          title: '首页触发勾选',
          moduleId: 'home-view',
          detail: 'checkbox 点击后调用 Tracking.toggleSection()。',
        },
        {
          title: '保存本地状态',
          moduleId: 'tracking',
          detail: '把完成数据写入本地存储，并计算 day 完成情况。',
        },
      ],
      starterQuestion: '为什么刷新后还能看到完成状态？',
    },
    {
      id: 'recording-flow',
      title: '录音如何从麦克风变成历史记录',
      summary: '从设备能力到浏览器本地数据库的一条完整链路。',
      moduleIds: ['home-view', 'recorder'],
      steps: [
        {
          title: '录音入口在首页',
          moduleId: 'home-view',
          detail: '每个练习 section 都会渲染录音 UI，并提供当前会话上下文。',
        },
        {
          title: '设备录音与持久化',
          moduleId: 'recorder',
          detail: '使用 MediaRecorder 生成 Blob，再写入 IndexedDB。',
        },
      ],
      starterQuestion: '录音为什么适合放 IndexedDB，而不是 localStorage？',
    },
  ],
  terms: [
    {
      id: 'entry-point',
      label: 'Entry Point',
      plain: '程序真正开始执行的入口文件或入口函数。',
      projectExample: 'Violin 的入口是 js/app.js 里的 init()。',
      moduleId: 'app-shell',
      checkYourself: '如果你想知道“页面最先创建了什么 DOM”，应该先从入口看。',
    },
    {
      id: 'routing',
      label: 'Routing',
      plain: '根据 URL 或 hash 决定当前该显示哪一页。',
      projectExample: 'router.js 把 #/plan、#/tuner、#/theory 等地址映射到对应 view。',
      moduleId: 'routing',
      checkYourself: '如果新增一个页面，通常要补 route 和 nav 两处。',
    },
    {
      id: 'data-model',
      label: 'Data Model',
      plain: '业务数据原本长什么样，以及字段怎样组织。',
      projectExample: 'lesson-current.js 里的 exercises、progression 就是这个项目的原始数据模型。',
      moduleId: 'lesson-data',
      checkYourself: '当你发现很多字段还没开始渲染，但已经先被定义出来时，你通常就在看 data model。',
    },
    {
      id: 'view-model',
      label: 'View Model',
      plain: '为了让页面更容易渲染，把原始数据重新整理成适合 UI 使用的结构。',
      projectExample: 'practice-plan.js 把 lesson 数据转换成首页 section 卡片需要的字段。',
      moduleId: 'practice-plan',
      checkYourself: '如果你看到代码在“补字段、改名字、算 badge”，通常就是在生成 view model。',
    },
    {
      id: 'view',
      label: 'View',
      plain: '负责渲染某个页面，并绑定该页面上的交互。',
      projectExample: 'home-view.js 把 daily plan 组装成首页。',
      moduleId: 'home-view',
      checkYourself: '当你看到很多 DOM 拼接和事件绑定时，通常就在 view 层。',
    },
    {
      id: 'state',
      label: 'State',
      plain: '系统在某个时刻记住的运行中信息。',
      projectExample: 'practicePlayer.state 记录当前是否在 demo、click 或 reference 模式。',
      moduleId: 'practice-player',
      checkYourself: '如果 UI 需要根据“现在正在发生什么”变化，你通常就在处理 state。',
    },
    {
      id: 'event-bus',
      label: 'Event Bus',
      plain: '一个模块发事件，另一个模块监听事件，从而减少直接耦合。',
      projectExample: 'practice-player 发出 practice:beat，home-view 监听后更新高亮。',
      moduleId: 'practice-player',
      checkYourself: '适合一对多通知，不适合承载混乱的业务真相。',
    },
    {
      id: 'timeline',
      label: 'Timeline',
      plain: '把一串内容按时间顺序展开，方便调度和同步。',
      projectExample: 'score-utils 把 measures 转成包含 startOffsetBeats 的 timeline events。',
      moduleId: 'score-utils',
      checkYourself: '如果要让 UI 高亮和音频播放对齐，timeline 很常见。',
    },
    {
      id: 'single-source-of-truth',
      label: 'Single Source of Truth',
      plain: '一个领域里只保留一份权威状态，避免多处状态彼此不一致。',
      projectExample: '播放相关状态统一收口到 practice-player，而不是散落在多个按钮里。',
      moduleId: 'practice-player',
      checkYourself: '当你发现两个地方都在记录“是否播放中”，通常意味着设计要收口。',
    },
    {
      id: 'persistence',
      label: 'Persistence',
      plain: '让数据在刷新页面后还能存在。',
      projectExample: 'tracking 用本地存储保存完成状态，recorder 用 IndexedDB 保存音频。',
      moduleId: 'tracking',
      checkYourself: '当你问“刷新以后为什么还在”时，本质就是 persistence。',
    },
  ],
  codeReadings: [
    {
      id: 'app-shell-view-shell',
      moduleId: 'app-shell',
      file: 'js/app.js',
      title: '统一创建 view 容器',
      excerpt: [
        "const views = {};",
        "['home', 'plan', 'tuner', 'progress', 'theory'].forEach((name) => {",
        "  const div = document.createElement('div');",
        "  div.id = `view-${name}`;",
        "  div.className = 'view';",
        "  main.appendChild(div);",
        "  views[name] = div;",
        "});",
      ].join('\n'),
      what: '先由应用壳层统一建立所有页面容器。',
      why: '页面结构由入口层统一管理，后续每个 view 只需要接管自己的 DOM 容器。',
      followUp: '看 HomeView.init(views.home)，理解容器是如何交给具体模块的。',
    },
    {
      id: 'app-shell-route-map',
      moduleId: 'app-shell',
      file: 'js/app.js',
      title: '用 routeMap 把 URL 接到模块',
      excerpt: [
        "const routeMap = {",
        "  '/': { view: 'home', module: HomeView, navRoute: '/' },",
        "  '/plan': { view: 'plan', module: PlanView, navRoute: '/plan' },",
        "};",
        "",
        "Object.entries(routeMap).forEach(([pattern, config]) => {",
        "  router.register(pattern, { ... });",
        "});",
      ].join('\n'),
      what: '把地址、页面容器和对应模块收口到一张映射表里。',
      why: '当页面变多时，入口层仍然只维护一张清楚的路由表，而不是散落很多条件判断。',
      followUp: '打开 js/router.js，看 register() 和 start() 如何消费这些配置。',
    },
    {
      id: 'routing-resolve',
      moduleId: 'routing',
      file: 'js/router.js',
      title: '先精确匹配，再尝试参数路由',
      excerpt: [
        "_resolve() {",
        "  const hash = location.hash.slice(1) || '/';",
        "  if (this._routes[hash]) {",
        "    this._activate(hash);",
        "    return;",
        "  }",
        "  for (const pattern of Object.keys(this._routes)) { ... }",
        "}",
      ].join('\n'),
      what: '先检查完全匹配的路由，再回退到带参数的模式匹配。',
      why: '这样写能让常见路径更直接，同时保留 /theory/:topic 这类可扩展能力。',
      followUp: '继续看 _matchPattern() 和 _activate()，理解参数是怎么传给 view 的。',
    },
    {
      id: 'event-bus-pubsub',
      moduleId: 'event-bus',
      file: 'js/event-bus.js',
      title: '极简发布订阅',
      excerpt: [
        "on(event, callback) {",
        "  (this._listeners[event] ||= []).push(callback);",
        "},",
        "",
        "emit(event, data) {",
        "  (this._listeners[event] || []).forEach((cb) => {",
        "    try { cb(data); } catch (e) { console.error(...); }",
        "  });",
        "}",
      ].join('\n'),
      what: '把“注册监听”和“广播事件”压缩到一个很小的对象里。',
      why: '这个项目只需要轻量协作，不需要复杂状态库；简单事件总线就够了。',
      followUp: '回到 home-view.js 和 practice-player.js，追 practice:statechange 的发送和消费。',
    },
    {
      id: 'lesson-data-single-object',
      moduleId: 'lesson-data',
      file: 'data/lesson-current.js',
      title: '用一个全局对象承载当前课程',
      excerpt: [
        "window.CURRENT_LESSON = {",
        "  weekOf: '2026-03-23',",
        "  lessonDay: 1,",
        "  exercises: [",
        "    { id: 'ex-open-strings', type: 'open-strings', progression: { day1: { ... } } },",
        "    { id: 'ex-trick-or-treat', type: 'piece', progression: { day1: { ... } } },",
        "  ]",
        "};",
      ].join('\n'),
      what: '当前课程内容被集中放进一个静态对象里，页面启动后直接读取。',
      why: '对单课程产品来说，这能把内容更新成本收口在一份数据文件里。',
      followUp: '顺着 exercises 和 progression 去看 practice-plan.js，观察它怎样把这些字段变成首页内容。',
    },
    {
      id: 'practice-plan-transform',
      moduleId: 'practice-plan',
      file: 'js/practice-plan.js',
      title: '把 lesson 转成 section 列表',
      excerpt: [
        "lesson.exercises.forEach((exercise) => {",
        "  const progression = exercise.progression?.[dayKey] || {};",
        "  const section = {",
        "    id: exercise.id,",
        "    title: exercise.title,",
        "    durationMinutes: Math.max(minutes, 2),",
        "  };",
        "  sections.push(section);",
        "});",
      ].join('\n'),
      what: '遍历原始练习数据，把每个 exercise 变成首页能直接消费的 section。',
      why: 'UI 不应该自己推导 lesson 数据细节，先做一次结构整理会让页面层更轻。',
      followUp: '看 piece 分支里如何额外补 bpm、mode、measures 这些页面字段。',
    },
    {
      id: 'home-view-show',
      moduleId: 'home-view',
      file: 'js/ui/home-view.js',
      title: '进入首页时先算 plan，再订阅事件',
      excerpt: [
        "_dayNumber = getDayNumber(_lesson.lessonDay);",
        "_plan = generateDailyPlan(_lesson, _dayNumber);",
        "render();",
        "",
        "EventBus.on('practice:beat', onPracticeBeat);",
        "EventBus.on('practice:notechange', onPracticeNoteChange);",
        "EventBus.on('practice:statechange', onPracticeStateChange);",
      ].join('\n'),
      what: '首页展示的第一步不是画 DOM，而是先生成当天 plan，再接入播放相关事件。',
      why: '这说明 home-view 更像装配层：一手拿 plan，一手接各种交互模块。',
      followUp: '继续看 renderSection()，理解不同练习类型怎样被分发到不同渲染函数。',
    },
    {
      id: 'home-view-render-section',
      moduleId: 'home-view',
      file: 'js/ui/home-view.js',
      title: '按 section 类型把能力拼回页面',
      excerpt: [
        "if (section.measures) {",
        "  renderPieceSection(card, section);",
        "}",
        "if (section.strings) {",
        "  renderStringsSection(card, section);",
        "}",
        "renderRecordingSection(card, section, getSessionContext());",
        "card.appendChild(createCompletionRow(card, section, isCompleted));",
      ].join('\n'),
      what: '首页不会把所有练习当成同一种东西，而是根据字段决定接哪套 UI 能力。',
      why: '这样一个 view 里既能兼容曲目练习，也能兼容空弦练习和录音、打勾等附加功能。',
      followUp: '点进 renderPieceSection()，看播放器和速度控制是怎样挂到卡片上的。',
    },
    {
      id: 'practice-player-start-demo',
      moduleId: 'practice-player',
      file: 'js/practice-player.js',
      title: '开始 demo 前先清掉旧 session',
      excerpt: [
        "async startDemo({ sectionId, measures, bpm, speedFactor = 1, beatsPerMeasure = 4 }) {",
        "  const ctx = await this._audio.ensureContext();",
        "  this._stopSession({ emitStateChange: false, stopAudio: this.running });",
        "  const timeline = buildPlaybackTimeline(measures, { beatsPerMeasure });",
        "  this._ctx = ctx;",
        "  this._timeline = timeline;",
        "  ...",
        "}",
      ].join('\n'),
      what: '每次进入 demo 前，先结束旧的播放 session，再为当前 section 建立新的时间线。',
      why: '这是 single source of truth 的关键动作，保证不会同时有两套播放状态在跑。',
      followUp: '继续看 _stopSession()，理解 stop、切模式、结束 demo 为什么都要走同一套清理逻辑。',
    },
    {
      id: 'practice-player-toggle-click',
      moduleId: 'practice-player',
      file: 'js/practice-player.js',
      title: '点击节拍器时先检查当前模式',
      excerpt: [
        "async toggleClick({ sectionId, bpm, speedFactor = 1, beatsPerMeasure = 4 }) {",
        "  if (this._state.mode === 'demo') {",
        "    return this.state;",
        "  }",
        "  if (this._state.mode === 'click' && this._state.sectionId === sectionId) {",
        "    this.stop();",
        "    return this.state;",
        "  }",
        "  return this.startClick({ sectionId, bpm, speedFactor, beatsPerMeasure });",
        "}",
      ].join('\n'),
      what: '不是每次点按钮都直接启动，而是先根据当前状态决定忽略、停止还是切换。',
      why: '状态机的价值就在这里：按钮行为不靠 if scattered in UI，而是集中在一处判断。',
      followUp: '对照 tests/practice-player.test.js，看 demo 与 click 互斥是怎样被验证的。',
    },
    {
      id: 'audio-engine-ensure-context',
      moduleId: 'audio-engine',
      file: 'js/audio-engine.js',
      title: '确保浏览器音频上下文已解锁',
      excerpt: [
        "async ensureContext() {",
        "  if (!this._ctx) {",
        "    const AudioContextClass = window.AudioContext || window.webkitAudioContext;",
        "    this._ctx = new AudioContextClass();",
        "    this._masterGain = this._ctx.createGain();",
        "  }",
        "  this._primeContextForGesture();",
        "  if (this._ctx.state === 'suspended' || this._ctx.state === 'interrupted') {",
        "    await this._ctx.resume();",
        "  }",
        "}",
      ].join('\n'),
      what: '先创建或恢复 AudioContext，再在手势链路里尝试做一次静默解锁。',
      why: '浏览器音频最容易出问题的就是上下文没解锁；这层把平台兼容性集中处理了。',
      followUp: '看 _primeContextForGesture() 和 _scheduleNote()，理解兼容性和真正发声是怎么分开的。',
    },
    {
      id: 'score-utils-cells',
      moduleId: 'score-utils',
      file: 'js/score-utils.js',
      title: '先把每个音符变成带时间偏移的 cell',
      excerpt: [
        "const cell = {",
        "  noteIndex,",
        "  pitch: note.pitch,",
        "  startBeat: measureBeatCursor + 1,",
        "  startOffsetBeats: globalBeatCursor,",
        "  endOffsetBeats: globalBeatCursor + beats,",
        "  spanUnits: Math.max(1, Math.round(beats * GRID_UNITS_PER_BEAT)),",
        "};",
      ].join('\n'),
      what: '先把原始 note 扩展成更完整的 cell，里面同时保存页面展示和播放调度需要的信息。',
      why: '一旦 startOffsetBeats / endOffsetBeats 这些字段统一好，UI 和播放器就能共享同一套时间线真相。',
      followUp: '继续看 buildPlaybackTimeline() 和 buildScoreModel()，观察它们如何消费同一批 cell。',
    },
    {
      id: 'music-theory-topics',
      moduleId: 'music-theory',
      file: 'js/music-theory.js',
      title: '把乐理说明当成结构化数据',
      excerpt: [
        "export const THEORY_TOPICS = [",
        "  { id: 'tempo', title: '速度记号和节拍', bullets: [ ... ] },",
        "  { id: 'techniques', title: '拨弦、拉弓和表情术语', bullets: [ ... ] },",
        "  { id: 'rests', title: '休止符', bullets: [ ... ] },",
        "];",
      ].join('\n'),
      what: '乐理内容不是写死在页面里的段落，而是先整理成结构化主题数据。',
      why: '这样一来，页面只是读数据；真正要改教学解释时，只用改一份源数据。',
      followUp: '再看 buildSpeedOptions()，体会“教学文案 + 业务规则”如何同时服务 UI。',
    },
    {
      id: 'tracking-toggle-section',
      moduleId: 'tracking',
      file: 'js/tracking.js',
      title: '切换完成状态时顺手广播事件',
      excerpt: [
        "toggleSection(weekOf, dayNumber, sectionId) {",
        "  const data = State.getWeekTracking(weekOf);",
        "  ...",
        "  day.sections[sectionId] = { completed: !wasCompleted };",
        "  State.saveWeekTracking(weekOf, data);",
        "  EventBus.emit('section:toggle', { weekOf, dayNumber, sectionId, completed: !wasCompleted });",
        "}",
      ].join('\n'),
      what: '一次打勾操作会同时完成三件事：读旧状态、写新状态、发出更新事件。',
      why: '持久化层不只是“存一下”，它还要把状态变化告诉其他模块，避免 UI 自己猜。',
      followUp: '继续看 _updateStats()，理解天数、连击和总时长是怎么累加的。',
    },
    {
      id: 'recorder-open-db',
      moduleId: 'recorder',
      file: 'js/recorder.js',
      title: '先建好 IndexedDB 结构，再存录音',
      excerpt: [
        "request.onupgradeneeded = (e) => {",
        "  const db = e.target.result;",
        "  if (!db.objectStoreNames.contains(STORE_NAME)) {",
        "    const store = db.createObjectStore(STORE_NAME, { keyPath: 'id', autoIncrement: true });",
        "    store.createIndex('exerciseId', 'exerciseId', { unique: false });",
        "    store.createIndex('dayNumber', 'dayNumber', { unique: false });",
        "  }",
        "};",
      ].join('\n'),
      what: '录音系统第一次启动时，会先准备一个能按练习、日期索引的本地数据库。',
      why: '录音不是小字符串，localStorage 不适合；IndexedDB 更适合存 Blob 和做检索。',
      followUp: '再看 stopRecording()，观察 Blob、duration 和元数据是怎样一起写入数据库的。',
    },
  ],
  tasks: [
    {
      id: 'task-theory-copy',
      title: '热身：改一条乐理说明',
      level: 'Warm-up',
      estimate: '10 分钟',
      goal: '先通过最小改动建立“改代码 -> 刷新页面 -> 看见结果”的反馈回路。',
      focusModuleIds: ['music-theory'],
      filePaths: ['js/music-theory.js', 'js/ui/theory-view.js'],
      steps: [
        '打开 THEORY_TOPICS，找到 tempo 或 rests 主题。',
        '改一条 summary 或 bullet，让文字更像你自己会说的话。',
        '刷新 #/theory 或首页里的理论入口，确认新文案出现。',
      ],
      verify: '页面里能看到新文案，没有语法报错。',
    },
    {
      id: 'task-daily-plan-trace',
      title: '追一遍今日计划生成链路',
      level: 'Warm-up',
      estimate: '15 分钟',
      goal: '理解 lesson data、practice-plan 和 home-view 之间的关系。',
      focusModuleIds: ['lesson-data', 'practice-plan', 'home-view'],
      filePaths: ['data/lesson-current.js', 'js/practice-plan.js', 'js/ui/home-view.js'],
      steps: [
        '先在 lesson-current.js 里找到 progression.day1。',
        '再看 practice-plan.js 如何把这一天的内容转换成 sections。',
        '最后在 home-view.js 里观察 sections 如何被 renderSection() 渲染。',
      ],
      verify: '你能用自己的话说出：数据、计划、页面三层分别负责什么。',
    },
    {
      id: 'task-speed-label',
      title: '动手：改速度标签或速度选项',
      level: 'Hands-on',
      estimate: '20 分钟',
      goal: '体验一个纯函数改动如何影响 UI 和测试。',
      focusModuleIds: ['music-theory', 'home-view'],
      filePaths: ['js/music-theory.js', 'tests/music-theory.test.js'],
      steps: [
        '查看 buildSpeedOptions()、formatSpeedLabel() 的输出规则。',
        '修改一个标签文案，或者新增一个标准速度档位。',
        '运行 node --test --experimental-default-type=module tests/*.test.js 验证变更。',
      ],
      verify: '相关测试通过，并且页面速度按钮显示符合预期。',
    },
    {
      id: 'task-playback-state',
      title: '深一点：理解播放状态机',
      level: 'Deep Dive',
      estimate: '30 分钟',
      goal: '把播放系统看成状态转换，而不是零散按钮逻辑。',
      focusModuleIds: ['practice-player', 'audio-engine', 'score-utils'],
      filePaths: ['js/practice-player.js', 'js/audio-engine.js', 'js/score-utils.js', 'tests/practice-player.test.js'],
      steps: [
        '先只看 practice-player.js 里的 public methods。',
        '画出 idle -> demo / click / reference 的转换关系。',
        '对照测试，理解为什么 stop() 和 toggleClick() 要做模式互斥。',
      ],
      verify: '你能解释：为什么播放状态必须集中管理，而不能由多个按钮自己记忆。',
    },
    {
      id: 'task-extend-learn-mode',
      title: '扩展学习模式本身',
      level: 'Hands-on',
      estimate: '20 分钟',
      goal: '通过给学习模式加内容，顺便练一次结构化前端改动。',
      focusModuleIds: ['app-shell'],
      filePaths: ['js/learn-data.js', 'js/ui/learn-view.js', 'tests/learn-data.test.js'],
      steps: [
        '在 learn-data.js 中新增一个术语、模块或练习任务。',
        '刷新 learning.html，确认新的卡片或按钮出现。',
        '运行 learn-data 测试，确保引用关系没有断。',
      ],
      verify: '学习模式能展示新内容，且 learn-data 测试通过。',
    },
  ],
  defaults: {
    moduleId: 'app-shell',
    flowId: 'daily-plan',
    termId: 'entry-point',
    taskId: 'task-theory-copy',
  },
};

export function buildLearningIndex(content = LEARNING_CONTENT) {
  const codeReadingsByModuleId = content.codeReadings.reduce((accumulator, item) => {
    (accumulator[item.moduleId] ||= []).push(item);
    return accumulator;
  }, {});

  return {
    modulesById: Object.fromEntries(content.modules.map((item) => [item.id, item])),
    flowsById: Object.fromEntries(content.flows.map((item) => [item.id, item])),
    termsById: Object.fromEntries(content.terms.map((item) => [item.id, item])),
    tasksById: Object.fromEntries(content.tasks.map((item) => [item.id, item])),
    codeReadingsByModuleId,
  };
}

export function buildLearningRelationships(content = LEARNING_CONTENT) {
  const moduleOrder = new Map(content.modules.map((module, index) => [module.id, index]));
  const outgoingById = Object.fromEntries(content.modules.map((module) => [module.id, [...module.dependsOn]]));
  const incomingById = Object.fromEntries(content.modules.map((module) => [module.id, []]));

  content.modules.forEach((module) => {
    module.dependsOn.forEach((dependencyId) => {
      if (incomingById[dependencyId]) {
        incomingById[dependencyId].push(module.id);
      }
    });
  });

  Object.keys(incomingById).forEach((moduleId) => {
    incomingById[moduleId].sort((left, right) => moduleOrder.get(left) - moduleOrder.get(right));
  });

  const edges = content.modules.flatMap((module) => module.dependsOn.map((dependencyId) => ({
    from: module.id,
    to: dependencyId,
  })));

  return {
    outgoingById,
    incomingById,
    edges,
  };
}

export function getLearningDefaults() {
  return { ...LEARNING_CONTENT.defaults };
}
